---
title: Multivariate Analysis of York Region's Broader Public Sector Energy Consumption
  Efficiency across Annual Time Series
author: "Alex Tan"
output:
  html_document: default
  pdf_document: default
---

# Introduction
Increasingly, cities utilize about 70% of comprehensive energy supply and planned proposals will house nearly 60% of world's population by 2030 (Seto and Dhakal 2014). Local government buildings provide initial testbeds for any policy initiatives of public sector and private sector before city-wide scale implementation.

Spatially, the York Region of Toronto and Buffalo-Niagara Falls Metropolitan Area have approximately the same size that qualifies as a large settlement area with a humid continental climate. Several policy initiatives on public buildings has been implemented on an ongoing basis or planned and a broad spectrum mapping are visualized.

Temporally, the data sets are provided in an open data license by the York Region municipal with an annual time series. The project will intend to visualize changes across time and conjecture predictive analytics.

As public sites provide supporting activities to sustain the function of a city, the project will query for efficiency in energy consumption through site clustering in broader public sector of York Region. The project will be objective on clustering effect and its’ efficiency on energy consumption and benchmarked compared to municipal government guideline.




# Visualization
Conceptual Visualization. The Second Draft will have better visualizations as I am working on the geocoding.
```{r, message=F, warning=F}
library(dplyr)
library(ggplot2)
library(maps)
library(ggmap)
library(spocc)
library(maps)
library(rgdal)
library(reshape)
# Load conceptual map
x=read.csv('data/2014_BPS_Reporting.csv')
x <- as.data.frame.matrix(x)
x$Address <- as.character(x$Address)
map = readOGR(dsn=path.expand("data/York.shp"))
head(x, 2)

#still trying to geocode coordinates in batch
#geocode test
coord <- matrix(ncol=3, nrow=86,byrow = T)
colnames(coord)<- c("id","long","lat")
coord[,1] <- c(1:86)
a <- x[,"Address"]
for(i in 1:86){
  tmp <- geocode(a[i])
  coord[i,2] <- tmp$lon
  coord[i,3] <-  tmp$lat
}
tidy.coord <- na.omit(coord)
tidy.coord <- as.data.frame(tidy.coord)
write.csv(tidy.coord,file = "data/coord.csv")
fortify(tidy.coord)
#conceptual visualization cluster

ggplot(tidy.coord,aes(x=long,y=lat))+
  geom_polygon(aes(x=long,y=lat,group=group),data=map,color="grey30")+
  geom_point(col="red")+
  coord_equal()

```

# Temporal Changes
The changes across the annual time-series will be shown here.



# Results
Some analytics along with the benchmark comparisons will be shown here at Second Draft.



# Conclusions
Broader Implication will be in Second Draft.



# References
Seto, K., & Dhakal , S. (2014, ). Human Settlements, Infrastructure, and Spatial Planning. Human Settlements, Infrastructure, and Spatial Planning. Retrieved 2017, from http://www.ipcc.ch/pdf/assessment-report/ar5/wg3/ipcc_wg3_ar5_chapter12.pdf
